// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/6cIN989hyn2
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Libre_Franklin } from 'next/font/google'
// import { Chivo } from 'next/font/google'

// libre_franklin({
//   subsets: ['latin'],
//   display: 'swap',
// })

// chivo({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"

// export function Navbar() {
//   return (
//     <div className="flex h-screen">
//       <main className="flex-1 p-8 md:p-12 lg:p-16">
//         <div className="max-w-[800px]">
//           <h1 className="text-4xl font-bold tracking-tight">Welcome to Our Website</h1>
//           <p className="mt-4 text-lg text-gray-500 dark:text-gray-400">
//             Discover the latest news, insights, and resources from our team.
//           </p>
//           <div className="mt-8 space-y-6">
//             <p>
//               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacinia, nisl
//               nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed euismod, nisl nec ultricies lacinia, nisl
//               nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.
//             </p>
//             <p>
//               Sed euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl. Sed
//               euismod, nisl nec ultricies lacinia, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.
//             </p>
//             <img src="/placeholder.svg" width="800" height="400" alt="Hero" className="rounded-xl object-cover" />
//           </div>
//         </div>
//       </main>
//       <nav className="bg-gray-100 p-8 md:p-12 lg:p-16 dark:bg-gray-800">
//         <div className="space-y-4">
//           <Link href="#" className="flex items-center gap-2 text-lg font-medium hover:underline" prefetch={false}>
//             <HomeIcon className="h-5 w-5" />
//             Home
//           </Link>
//           <Link href="#" className="flex items-center gap-2 text-lg font-medium hover:underline" prefetch={false}>
//             <NewspaperIcon className="h-5 w-5" />
//             News
//           </Link>
//           <Link href="#" className="flex items-center gap-2 text-lg font-medium hover:underline" prefetch={false}>
//             <InfoIcon className="h-5 w-5" />
//             About
//           </Link>
//           <Link href="#" className="flex items-center gap-2 text-lg font-medium hover:underline" prefetch={false}>
//             <ContactIcon className="h-5 w-5" />
//             Contact
//           </Link>
//         </div>
//       </nav>
//     </div>
//   )
// }

// function ContactIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M17 18a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2" />
//       <rect width="18" height="18" x="3" y="4" rx="2" />
//       <circle cx="12" cy="10" r="2" />
//       <line x1="8" x2="8" y1="2" y2="4" />
//       <line x1="16" x2="16" y1="2" y2="4" />
//     </svg>
//   )
// }


// function HomeIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
//       <polyline points="9 22 9 12 15 12 15 22" />
//     </svg>
//   )
// }


// function InfoIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="12" cy="12" r="10" />
//       <path d="M12 16v-4" />
//       <path d="M12 8h.01" />
//     </svg>
//   )
// }


// function NewspaperIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-2 2Zm0 0a2 2 0 0 1-2-2v-9c0-1.1.9-2 2-2h2" />
//       <path d="M18 14h-8" />
//       <path d="M15 18h-5" />
//       <path d="M10 6h8v4h-8V6Z" />
//     </svg>
//   )
// }
